version: '3.9'

services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: POSTGRES__USER
      POSTGRES_PASSWORD: POSTGRES__PASSWORD
      POSTGRES_DB: POSTGRES__DATABASE_NAME
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db_data: