version: '3.9'

services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 223456
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
volumes:
  db_data:
